"""
PDF exporter using WeasyPrint
"""

try:
    from weasyprint import HTML, CSS
    WEASYPRINT_AVAILABLE = True
    WEASYPRINT_ERROR = None
except Exception as e:
    WEASYPRINT_AVAILABLE = False
    WEASYPRINT_ERROR = str(e)
    HTML = None
    CSS = None

from typing import List, Dict
import os
from datetime import datetime


class PDFExporter:
    """Export content to PDF"""
    
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        
        if not WEASYPRINT_AVAILABLE:
            print(f"⚠️  WARNING: WeasyPrint is not available: {WEASYPRINT_ERROR}")
            print("📄 PDF generation will not work. Install GTK runtime on Windows.")
            print("📖 See WINDOWS_SETUP.md for installation instructions.")
    
    def export(
        self,
        pages: List[Dict],
        output_filename: str,
        include_toc: bool = True,
        include_cover: bool = True,
        custom_title: str = None
    ) -> str:
        """
        Export pages to PDF
        
        Args:
            pages: List of page dicts with 'title', 'html', 'url', 'metadata'
            output_filename: Output PDF filename
            include_toc: Include table of contents
            include_cover: Include cover page
            custom_title: Custom document title
            
        Returns:
            Path to generated PDF
            
        Raises:
            RuntimeError: If WeasyPrint is not available
        """
        if not WEASYPRINT_AVAILABLE:
            raise RuntimeError(
                f"PDF generation is not available: {WEASYPRINT_ERROR}\n\n"
                "On Windows, you need to install GTK runtime libraries.\n"
                "See WINDOWS_SETUP.md for installation instructions.\n\n"
                "Quick fix: Download and install GTK from:\n"
                "https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases\n\n"
                "Alternative: Use Docker with 'docker-compose up' for zero-config setup."
            )
        
        # Build HTML document
        html_content = self._build_html(
            pages,
            include_toc=include_toc,
            include_cover=include_cover,
            custom_title=custom_title
        )
        
        # Generate PDF
        output_path = os.path.join(self.output_dir, output_filename)
        
        HTML(string=html_content).write_pdf(
            output_path,
            stylesheets=[CSS(string=self._get_pdf_styles())]
        )
        
        return output_path
    
    def _build_html(
        self,
        pages: List[Dict],
        include_toc: bool,
        include_cover: bool,
        custom_title: str
    ) -> str:
        """Build complete HTML document"""
        html_parts = ['<!DOCTYPE html><html><head><meta charset="UTF-8">']
        
        title = custom_title or pages[0]['title'] if pages else 'DocForge Export'
        html_parts.append(f'<title>{title}</title>')
        html_parts.append('</head><body>')
        
        # Cover page
        if include_cover:
            html_parts.append(self._generate_cover_page(title, pages))
        
        # Table of contents
        if include_toc and len(pages) > 1:
            html_parts.append(self._generate_toc(pages))
        
        # Content pages
        for i, page in enumerate(pages, 1):
            html_parts.append(f'<div class="page" id="page-{i}">')
            html_parts.append(f'<h1 class="page-title">{page["title"]}</h1>')
            html_parts.append(page['html'])
            html_parts.append(f'<div class="page-footer">')
            html_parts.append(f'<span>{page["metadata"]["url"]}</span>')
            html_parts.append(f'<span>Page {i}</span>')
            html_parts.append('</div>')
            html_parts.append('</div>')
        
        html_parts.append('</body></html>')
        
        return ''.join(html_parts)
    
    def _generate_cover_page(self, title: str, pages: List[Dict]) -> str:
        """Generate cover page HTML"""
        now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        page_count = len(pages)
        
        return f'''
        <div class="cover-page">
            <h1 class="cover-title">{title}</h1>
            <p class="cover-info">Generated by DocForge</p>
            <p class="cover-info">{now}</p>
            <p class="cover-info">{page_count} pages</p>
        </div>
        <div class="page-break"></div>
        '''
    
    def _generate_toc(self, pages: List[Dict]) -> str:
        """Generate table of contents"""
        toc = ['<div class="toc"><h2>Table of Contents</h2><ul>']
        
        for i, page in enumerate(pages, 1):
            toc.append(f'<li><a href="#page-{i}">{page["title"]}</a></li>')
        
        toc.append('</ul></div>')
        toc.append('<div class="page-break"></div>')
        
        return ''.join(toc)
    
    def _get_pdf_styles(self) -> str:
        """Get PDF-specific CSS styles"""
        return '''
        @page {
            size: A4;
            margin: 2cm;
        }
        
        body {
            font-family: "Helvetica", "Arial", sans-serif;
            font-size: 12pt;
            line-height: 1.6;
            color: #333;
        }
        
        .cover-page {
            text-align: center;
            padding-top: 200px;
        }
        
        .cover-title {
            font-size: 36pt;
            font-weight: bold;
            margin-bottom: 50px;
        }
        
        .cover-info {
            font-size: 14pt;
            color: #666;
            margin: 10px 0;
        }
        
        .page-break {
            page-break-after: always;
        }
        
        .page {
            page-break-before: always;
        }
        
        .page-title {
            font-size: 24pt;
            font-weight: bold;
            margin-bottom: 20px;
            color: #2c3e50;
        }
        
        .page-footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 9pt;
            color: #999;
            display: flex;
            justify-content: space-between;
        }
        
        .toc {
            padding: 20px 0;
        }
        
        .toc h2 {
            font-size: 20pt;
            margin-bottom: 20px;
        }
        
        .toc ul {
            list-style: none;
            padding-left: 0;
        }
        
        .toc li {
            margin: 10px 0;
            font-size: 12pt;
        }
        
        .toc a {
            color: #3498db;
            text-decoration: none;
        }
        
        img {
            max-width: 100%;
            height: auto;
        }
        
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: "Courier New", monospace;
            font-size: 10pt;
        }
        
        pre {
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-size: 10pt;
        }
        
        pre code {
            background: none;
            padding: 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        
        th {
            background: #f8f9fa;
            font-weight: bold;
        }
        '''
