name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation"]
assignees:
  - Ishan96Dev
body:
  - type: markdown
    attributes:
      value: |
        Help us improve DocForge documentation! Report any issues with our docs below.
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README.md
        - API Documentation
        - Architecture Documentation
        - Deployment Guide
        - Quick Start Guide
        - User Guide
        - Code Comments
        - Contributing Guidelines
        - Other
    validations:
      required: true
  
  - type: input
    id: doc-location
    attributes:
      label: Document Location
      description: Provide the file path or URL of the documentation
      placeholder: ex. docs/API.md or https://example.com/docs
    validations:
      required: true
  
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect/Outdated Information
        - Unclear/Confusing Explanation
        - Broken Links
        - Typo/Grammar
        - Missing Examples
        - Technical Inaccuracy
        - Other
    validations:
      required: true
  
  - type: textarea
    id: current-content
    attributes:
      label: Current Documentation
      description: Copy the current documentation text that needs improvement (if applicable)
      placeholder: Paste the current text here...
      render: markdown
    validations:
      required: false
  
  - type: textarea
    id: issue-description
    attributes:
      label: What's Wrong?
      description: Describe the documentation issue in detail
      placeholder: |
        The documentation states... but it should say...
        This section is confusing because...
        The example is missing...
    validations:
      required: true
  
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        The documentation should explain...
        Add an example showing...
        Update the text to...
    validations:
      required: true
  
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What should users be able to understand after the improvement?
      placeholder: After this change, users should be able to...
    validations:
      required: false
  
  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is affected by this documentation issue?
      options:
        - New Users
        - Developers
        - Contributors
        - System Administrators
        - All Users
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Screenshots, links to related documentation, etc.
    validations:
      required: false
  
  - type: checkboxes
    id: contribution-willingness
    attributes:
      label: Contribution
      description: Would you like to help improve this documentation?
      options:
        - label: I would be willing to submit a pull request to fix this
          required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this documentation issue hasn't been reported before
          required: true
        - label: I have provided specific details about the issue
          required: true
