name: Feature Request
description: Suggest a new feature or enhancement for DocForge
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees:
  - Ishan96Dev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area would this feature affect?
      options:
        - Backend API
        - Frontend UI/UX
        - Crawler Functionality
        - PDF Export
        - Content Rendering
        - Configuration/Settings
        - Performance
        - Documentation
        - DevOps/Deployment
        - Other
    validations:
      required: true
  
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the pain point or limitation.
      placeholder: I'm frustrated when... / It would be helpful if... / Currently, users cannot...
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        I would like to see...
        This feature should work by...
        The expected behavior is...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I also considered...
        Another approach could be...
        Current workaround is...
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority/Urgency
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true
  
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        Use Case 1: When crawling large documentation sites...
        Use Case 2: When exporting to PDF...
        Use Case 3: For team collaboration...
    validations:
      required: true
  
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide to users?
      placeholder: |
        - Improved performance
        - Better user experience
        - Saves time
        - Enables new workflows
    validations:
      required: false
  
  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have technical ideas on how to implement this, share them here
      placeholder: |
        This could be implemented by...
        Technologies that might help...
        API changes needed...
    validations:
      required: false
  
  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add any mockups, screenshots, or examples from other tools
      placeholder: Attach images or provide links to similar features in other applications
    validations:
      required: false
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature
          required: false
        - label: I would be willing to help test this feature
          required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been requested before
          required: true
        - label: This feature aligns with DocForge's purpose and goals
          required: true
